package nl.knaw.dans.easy.web.statistics;

public enum StatisticsEvent {
    START_PAGE_VISIT, USER_URL_REQUEST, USER_LOGIN, USER_LOGOUT, DOWNLOAD_DATASET_REQUEST, DOWNLOAD_FILE_REQUEST, SEARCH_TERM, ADVANCED_SEARCH_TERM, DATASET_DEPOSIT, FILE_DEPOSIT, DATASET_PUBLISHED, DATASET_VIEWED, USER_REGISTRATION, ASSIGN_USER_TO_GROUP
}
