package nl.knaw.dans.easy.mock;

import static org.easymock.EasyMock.expect;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;

import nl.knaw.dans.common.lang.repo.DmoStoreEventListener;
import nl.knaw.dans.common.lang.repo.DmoStoreId;
import nl.knaw.dans.easy.data.Data;
import nl.knaw.dans.easy.data.migration.MigrationRepo;
import nl.knaw.dans.easy.data.store.EasyStore;
import nl.knaw.dans.easy.data.store.FileStoreAccess;
import nl.knaw.dans.easy.data.userrepo.EasyUserRepo;
import nl.knaw.dans.easy.domain.model.Dataset;
import nl.knaw.dans.easy.domain.model.FileItem;
import nl.knaw.dans.easy.servicelayer.services.ItemService;
import nl.knaw.dans.easy.servicelayer.services.Services;

import org.junit.Before;
import org.junit.Test;
import org.powermock.api.easymock.PowerMock;
import org.powermock.modules.junit4.PowerMockRunner;

/**
 * Provides a fluent interface to mock a static configuration of repository objects. See demo test
 * classes for usage examples and troubleshooting.
 */
public class BusinessMocker
{
    private List<Dataset> mockedDatasets;
    private int fileCounter;

    /**
     * Initializes mocked services. Typically called by a {@link Test} method or a {@link Before} method
     * of a {@link PowerMockRunner} class. Call {@link PowerMock#replayAll(Object...) } between
     * configuring the desired mocked objects and executing your test. After completion of the test you
     * may want to call {@link PowerMock#verifyAll(Object...) }.
     * 
     * @throws Exception
     */
    public BusinessMocker() throws Exception
    {
        mockedDatasets = new LinkedList<Dataset>();

        Data.unlock();
        Services.unlock();
        // TRIED PowerMock.mockStatic(Data.class);
        // before revision 12014 while this class was still a superclass for test classes
        // it only worked when everything was reduced into a single class
        // using setters did worked with expectations in the individual classes

        new Services().setItemService(PowerMock.createMock(ItemService.class));
        new Data().setUserRepo(PowerMock.createMock(EasyUserRepo.class));
        new Data().setEasyStore(PowerMock.createMock(EasyStore.class));
        new Data().setFileStoreAccess(PowerMock.createMock(FileStoreAccess.class));
        new Data().setMigrationRepo(PowerMock.createMock(MigrationRepo.class));

        expect(Data.getEasyStore().getListeners()).andStubReturn(new ArrayList<DmoStoreEventListener>());
    }

    /**
     * Creates an object to configure possible/expected behavior of the mocked services related to a
     * user.
     * 
     * @param userId
     * @throws Exception
     */
    public UserMocker user(final String userId) throws Exception
    {
        return new UserMocker(userId);
    }

    /**
     * Creates an object to configure possible/expected behavior of a mocked {@link Dataset} and related
     * services.
     * 
     * @param datasetId
     * @return
     * @throws Exception
     */
    public DatasetMocker dataset(final String datasetId) throws Exception
    {
        final DatasetMocker datasetMocker = new DatasetMocker(datasetId);
        mockedDatasets.add(datasetMocker.getDataset());
        return datasetMocker;
    }

    /**
     * Creates an object to configure possible/expected behavior of the mocked services related to a
     * file. The file gets a generated {@link DmoStoreId}.
     * 
     * @param path
     *        of the the file within the dataset
     * @return
     * @throws Exception
     */
    public FileMocker file(final String path) throws Exception
    {
        return new FileMocker(path, FileItem.NAMESPACE + ":" + ++fileCounter);
    }

    /**
     * Creates an object to configure possible/expected behavior of the mocked services related to a
     * file.
     * 
     * @param path
     *        of the the file within the dataset
     * @param id
     *        the value for the {@link DmoStoreId} of the file. The name space should not equal
     *        {@link FileItem#NAMESPACE} to avoid clashes with IDs generated by {@link #file(String)}.
     * @return
     * @throws Exception
     */
    public FileMocker file(final String path, final String id) throws Exception
    {
        if (id.startsWith(FileItem.NAMESPACE + ":"))
            throw new IllegalArgumentException("possible clash with generated IDs, choose another namespace than: " + FileItem.NAMESPACE);
        return new FileMocker(path, id);
    }

    /**
     * @return the mocked dataset objects.
     */
    public List<Dataset> getDatasets()
    {
        return mockedDatasets;
    }
}
